apiVersion: apps/v1
kind: Deployment
metadata:
  name: nghiahv-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nghiahv1-app
  template:
    metadata:
      labels:
        app: nghiahv1-app
    spec:
      containers:
      - name: nghiahv1-container
        # image: nghiahv1/project5:${CIRCLE_WORKFLOW_ID:0:7}
        image: nghiahv1/microproject:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80