apiVersion: apps/v1
kind: Deployment
metadata:
  name: nghiahv-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nghiahv-deployment
  template:
    metadata:
      labels:
        app: nghiahv-deployment
    spec:
      containers:
      - name: nghiahv1-container
        # image: nghiahv1/project5:TAGIMAGE
        image: nghiahv1/project5:f6740d1
        # image: nghiahv1/microproject:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80