apiVersion: apps/v1
kind: Deployment
metadata:
  name: nghiahv1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nghiahv1-app
  template:
    metadata:
      labels:
        app: nghiahv1-app
    spec:
      containers:
      - name: nghiahv1-container
        image: nghiahv1/project4:latest
        ports:
        - containerPort: 80