apiVersion: apps/v1
kind: Deployment
metadata:
  name: nghiahv-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nghiahv1-app
  template:
    metadata:
      labels:
        app: nghiahv1-app
    spec:
      containers:
      - name: nghiahv1-container
        image: nghiahv1/microproject:latest
        ports:
        - containerPort: 80